dist: bionic
language: node_js
node_js:
  - '12.8.0'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - npm ci
  - commitlint-travis

notifications:
  email:
    on_success: change
    on_failure: change
